/** Import catalog for Lab /helpers — mirrors docs/api.md §20.
 *  Copy lives in locales/fragments/helpers-catalog.*.js (usage / about / groups).
 */

export const IMPORT_CATALOG = [
  {
    id: "pulse",
    pkg: "@jacare/core",
    groupId: "reactivity",
    name: "pulse",
    importLine: "import { pulse } from '@jacare/core'",
    example: "import { pulse } from '@jacare/core'\n\nconst count = pulse(0)\ncount()           // → 0\ncount.set(1)      // → 1\ncount.update(n => n + 1)  // → 2",
    path: "/reactivity",
  },
  {
    id: "signal",
    pkg: "@jacare/core",
    groupId: "reactivity",
    name: "signal",
    importLine: "import { signal } from '@jacare/core'",
    example: "import { signal } from '@jacare/core'\n\nconst open = signal(false)\nopen()\nopen.set(true)",
    path: "/reactivity",
  },
  {
    id: "derive",
    pkg: "@jacare/core",
    groupId: "reactivity",
    name: "derive",
    importLine: "import { derive } from '@jacare/core'",
    example: "import { pulse, derive } from '@jacare/core'\n\nconst n = pulse(2)\nconst doubled = derive(() => n() * 2)\ndoubled()  // → 4\ndoubled.dispose()",
    path: "/reactivity",
  },
  {
    id: "computed",
    pkg: "@jacare/core",
    groupId: "reactivity",
    name: "computed",
    importLine: "import { computed } from '@jacare/core'",
    example: "import { pulse, computed } from '@jacare/core'\n\nconst price = pulse(10)\nconst tax = computed(() => price() * 0.1)\ntax.dispose()",
    path: "/reactivity",
  },
  {
    id: "effect",
    pkg: "@jacare/core",
    groupId: "reactivity",
    name: "effect",
    importLine: "import { effect } from '@jacare/core'",
    example: "import { pulse, effect } from '@jacare/core'\n\nconst n = pulse(0)\nconst { dispose } = effect(() => {\n  console.log('n is', n())\n})\n// later: dispose()",
    path: "/reactivity",
  },
  {
    id: "watch",
    pkg: "@jacare/core",
    groupId: "reactivity",
    name: "watch",
    importLine: "import { watch } from '@jacare/core'",
    example: "import { pulse, watch } from '@jacare/core'\n\nconst title = pulse('Hi')\nwatch(() => {\n  document.title = title()\n})",
    path: "/reactivity",
  },
  {
    id: "batch",
    pkg: "@jacare/core",
    groupId: "reactivity",
    name: "batch",
    importLine: "import { batch } from '@jacare/core'",
    example: "import { pulse, batch, effect } from '@jacare/core'\n\nconst a = pulse(0)\nconst b = pulse(0)\neffect(() => console.log(a() + b()))\n\nbatch(() => {\n  a.set(1)\n  b.set(2)\n})  // effect runs once → 3",
    path: "/reactivity",
  },
  {
    id: "enablePatience",
    pkg: "@jacare/core",
    groupId: "reactivity",
    name: "enablePatience",
    importLine: "import { enablePatience, flushSync, disablePatience } from '@jacare/core'",
    example: "import { pulse, effect, enablePatience, flushSync } from '@jacare/core'\n\nenablePatience()\nconst count = pulse(0)\neffect(() => console.log(count()))\n\ncount.set(1)\ncount.set(2)\ncount.set(3)\n// log not yet — pending microtask\nflushSync()  // logs 3 once",
    path: "/reactivity",
  },
  {
    id: "flushSync",
    pkg: "@jacare/core",
    groupId: "reactivity",
    name: "flushSync",
    importLine: "import { flushSync } from '@jacare/core'",
    example: "import { flushSync } from '@jacare/core'\n\ncount.set(1)\nflushSync()\nexpect(label.textContent).toBe('1')",
    path: "/reactivity",
  },
  {
    id: "disablePatience",
    pkg: "@jacare/core",
    groupId: "reactivity",
    name: "disablePatience",
    importLine: "import { disablePatience } from '@jacare/core'",
    example: "import { disablePatience } from '@jacare/core'\n\ndisablePatience()",
    path: "/reactivity",
  },
  {
    id: "isPatienceEnabled",
    pkg: "@jacare/core",
    groupId: "reactivity",
    name: "isPatienceEnabled",
    importLine: "import { isPatienceEnabled } from '@jacare/core'",
    example: "import { isPatienceEnabled, enablePatience } from '@jacare/core'\n\nenablePatience()\nisPatienceEnabled() // true",
    path: "/reactivity",
  },
  {
    id: "runAsLane",
    pkg: "@jacare/core",
    groupId: "reactivity",
    name: "runAsLane",
    importLine: "import { runAsLane } from '@jacare/core'",
    example: "import { pulse, runAsLane, enablePatience, flushSync } from '@jacare/core'\n\nenablePatience()\nconst bg = pulse(0)\nrunAsLane('idle', () => bg.set(1))\nflushSync()  // drains idle too",
    path: "/reactivity",
  },
  {
    id: "untrack",
    pkg: "@jacare/core",
    groupId: "reactivity",
    name: "untrack",
    importLine: "import { untrack } from '@jacare/core'",
    example: "import { pulse, effect, untrack } from '@jacare/core'\n\nconst a = pulse(1)\nconst b = pulse(2)\neffect(() => {\n  console.log(a(), untrack(() => b()))\n  // only a() triggers re-runs\n})",
    path: "/reactivity",
  },
  {
    id: "ReactiveCycleError",
    pkg: "@jacare/core",
    groupId: "reactivity",
    name: "ReactiveCycleError",
    importLine: "import { ReactiveCycleError } from '@jacare/core'",
    example: "import { pulse, effect, ReactiveCycleError } from '@jacare/core'\n\nconst a = pulse(0)\nconst b = pulse(0)\neffect(() => { a(); b.set(b() + 1) })\neffect(() => { b(); a.set(a() + 1) })\n\ntry {\n  a.set(1)\n} catch (error) {\n  if (error instanceof ReactiveCycleError) console.warn(error.message)\n}",
    path: "/reactivity",
  },
  {
    id: "createBag",
    pkg: "@jacare/core",
    groupId: "pulseBags",
    name: "createBag",
    importLine: "import { createBag, pulse } from '@jacare/core'",
    example: "import { createBag, pulse } from '@jacare/core'\n\nexport const cart = createBag('cart', () => ({\n  count: pulse(0),\n  total: pulse(0),\n}))\n\ncart.count.set(3)",
    path: "/bag",
  },
  {
    id: "getBag",
    pkg: "@jacare/core",
    groupId: "pulseBags",
    name: "getBag",
    importLine: "import { getBag } from '@jacare/core'",
    example: "import { getBag } from '@jacare/core'\n\nconst cart = getBag('cart')\ncart?.count()  // → current count",
    path: "/bag",
  },
  {
    id: "listBags",
    pkg: "@jacare/core",
    groupId: "pulseBags",
    name: "listBags",
    importLine: "import { listBags } from '@jacare/core'",
    example: "import { listBags } from '@jacare/core'\n\nlistBags()  // → ['cart', 'theme', …]",
    path: "/bag",
  },
  {
    id: "ripple",
    pkg: "@jacare/core",
    groupId: "pulseBags",
    name: "ripple",
    importLine: "import { ripple } from '@jacare/core'",
    example: "import { ripple } from '@jacare/core'\nimport { cart } from './bags.js'\n\nripple(() => {\n  cart.items.set([])\n})",
    path: "/bag",
  },
  {
    id: "bagSnap",
    pkg: "@jacare/core",
    groupId: "pulseBags",
    name: "bag.snap / hydrate / reset",
    importLine: "(methods on a bag instance)",
    example: "const data = cart.snap()\nlocalStorage.setItem('cart', JSON.stringify(data))\n\ncart.hydrate(JSON.parse(localStorage.getItem('cart')))\ncart.reset()",
    path: "/bag",
  },
  {
    id: "bagKey",
    pkg: ".jcr template",
    groupId: "pulseBags",
    name: "${@bag/key}",
    importLine: "(Mesh address in templates)",
    example: "<span>Items: ${@cart/count}</span>\n<button on-click=${() => cart.count.update(n => n + 1)}>\n  Add\n</button>",
    path: "/bag",
  },
  {
    id: "bindText",
    pkg: "@jacare/core",
    groupId: "dom",
    name: "bindText",
    importLine: "Emitted from ${expr} text",
    example: "<!-- .jcr -->\n<span>${count}</span>\n\n<!-- roughly emitted -->\nbindText(node, () => count())",
    path: "/bindings",
  },
  {
    id: "bindAttribute",
    pkg: "@jacare/core",
    groupId: "dom",
    name: "bindAttribute",
    importLine: "Emitted from :attr=${expr}",
    example: "<!-- .jcr -->\n<a :href=${url} :title=${label}>Open</a>",
    path: "/bindings",
  },
  {
    id: "bindClass",
    pkg: "@jacare/core",
    groupId: "dom",
    name: "bindClass",
    importLine: "Emitted from class-name=${bool}",
    example: "<!-- .jcr -->\n<div class-open=${open} class-busy=${loading}>…</div>",
    path: "/bindings",
  },
  {
    id: "bindStyleVar",
    pkg: "@jacare/core",
    groupId: "dom",
    name: "bindStyleVar",
    importLine: "Emitted from style---name=${expr}",
    example: "<!-- .jcr -->\n<div style---pct=${pct}>…</div>\n/* CSS: width: calc(var(--pct) * 1%) */",
    path: "/bindings",
  },
  {
    id: "bindModel",
    pkg: "@jacare/core",
    groupId: "dom",
    name: "bindModel",
    importLine: "Emitted from bind-value / bind-checked",
    example: "<!-- .jcr -->\n<input bind-value=${name} />\n<input type=\"checkbox\" bind-checked=${ok} />",
    path: "/bindings",
  },
  {
    id: "branch",
    pkg: "@jacare/core",
    groupId: "controlFlow",
    name: "branch / showIf",
    importLine: "Emitted from #if / #case",
    example: "#if loading()\n  <p>Loading…</p>\n#elif error()\n  <p>Error</p>\n#else\n  <p>Ready</p>\n#end",
    path: "/if",
  },
  {
    id: "reconcileKeyedList",
    pkg: "@jacare/core",
    groupId: "controlFlow",
    name: "reconcileKeyedList",
    importLine: "Emitted from #for",
    example: "#for items() as item (item.id)\n  <li>${item.name}</li>\n#end",
    path: "/for",
  },
  {
    id: "mountSlot",
    pkg: "@jacare/core",
    groupId: "slots",
    name: "mountSlot",
    importLine: "Emitted from <slot>",
    example: "<!-- parent -->\n<Card>\n  <slot name=\"title\">Hello</slot>\n  <p>Body</p>\n</Card>\n\n<!-- Card.jcr -->\n<header><slot name=\"title\" /></header>\n<slot />",
    path: "/components",
  },
  {
    id: "createNav",
    pkg: "@jacare/core",
    groupId: "navigation",
    name: "createNav",
    importLine: "import { createNav } from '@jacare/core'",
    example: "import { createNav, lazy, screen } from '@jacare/core'\nimport Shell from './Shell.jcr'\nimport Home from './Home.jcr'\n\nexport const nav = createNav({\n  layout: Shell,\n  screens: {\n    '/': { use: screen(Home), title: 'Home' },\n    '/about': { use: lazy(() => import('./About.jcr')), title: 'About' },\n  },\n})",
    path: "/nav",
  },
  {
    id: "lazy",
    pkg: "@jacare/core",
    groupId: "navigation",
    name: "lazy",
    importLine: "import { lazy } from '@jacare/core'",
    example: "lazy(() => import('./About.jcr'))",
    path: "/nav",
  },
  {
    id: "screen",
    pkg: "@jacare/core",
    groupId: "navigation",
    name: "screen",
    importLine: "import { screen } from '@jacare/core'",
    example: "import Home from './Home.jcr'\nscreen(Home)",
    path: "/nav",
  },
  {
    id: "navMethods",
    pkg: "@jacare/core",
    groupId: "navigation",
    name: "nav.attach / go / swap / undo / warm",
    importLine: "(methods on createNav() instance)",
    example: "nav.attach(document.getElementById('app'))\nnav.go('/about')\nnav.go('/settings', { focus: true })  // focus [data-jacare-focus]\nnav.warm('/cart')   // preload\nnav.undo()          // back",
    path: "/nav",
  },
  {
    id: "createRoute",
    pkg: "@jacare/core",
    groupId: "navigation",
    name: "createRoute",
    importLine: "import { createRoute } from '@jacare/core'",
    example: "import { createRoute } from '@jacare/core'\nimport { nav } from './nav.js'\n\nexport const route = createRoute(nav.where)",
    path: "/nav",
  },
  {
    id: "getRouteParam",
    pkg: "@jacare/core",
    groupId: "navigation",
    name: "getRouteParam",
    importLine: "import { getRouteParam } from '@jacare/core'",
    example: "import { getRouteParam } from '@jacare/core'\n\nconst id = getRouteParam('id')\nid()  // → '42' when path is /orders/42\n\n// template:\n// <p>${@route/id}</p>",
    path: "/nav",
  },
  {
    id: "routeParam",
    pkg: "@jacare/core",
    groupId: "navigation",
    name: "routeParam",
    importLine: "import { routeParam } from '@jacare/core'",
    example: "import { routeParam } from '@jacare/core'\nimport { route } from './route.js'\n\nconst id = routeParam(route, 'id')\nid()  // → '42' when path is /item/42",
    path: "/nav",
  },
  {
    id: "routeSearch",
    pkg: "@jacare/core",
    groupId: "navigation",
    name: "routeSearch",
    importLine: "import { routeSearch } from '@jacare/core'",
    example: "import { routeSearch } from '@jacare/core'\nimport { route } from './route.js'\n\nconst q = routeSearch(route, 'q')\nq()  // → 'tea' when URL has ?q=tea",
    path: "/nav",
  },
  {
    id: "routeHref",
    pkg: "@jacare/core",
    groupId: "navigation",
    name: "routeHref",
    importLine: "import { routeHref } from '@jacare/core'",
    example: "import { routeHref } from '@jacare/core'\n\nrouteHref('/item/:id', { id: '7' })              // → '/item/7'\nrouteHref('/a/:idea/:id', { idea: 'x', id: '1' }) // → '/a/x/1'\nrouteHref('/files/:path*', { path: 'a/b' })       // → '/files/a/b'",
    path: "/nav",
  },
  {
    id: "navTitle",
    pkg: "@jacare/core",
    groupId: "navigation",
    name: "setNavTitle / getNavTitle",
    importLine: "import { setNavTitle, getNavTitle } from '@jacare/core'",
    example: "import { setNavTitle, getNavTitle, effect } from '@jacare/core'\n\neffect(() => {\n  setNavTitle(`Cart · ${count()}`)\n})\ngetNavTitle()  // current title string",
    path: "/lifecycle",
  },
  {
    id: "jacareAttrs",
    pkg: ".jcr template",
    groupId: "navigation",
    name: "jacare-frame / jacare-go / jacare-here",
    importLine: "(attributes in view)",
    example: "<main jacare-frame></main>\n<a jacare-go=\"/about\" href=\"/about\">About</a>\n<a jacare-go=\"/shop\" jacare-here class-active>Shop</a>",
    path: "/nav",
  },
  {
    id: "createForm",
    pkg: "@jacare/core",
    groupId: "forms",
    name: "createForm",
    importLine: "import { createForm } from '@jacare/core'",
    example: "import { createForm } from '@jacare/core'\n\nconst form = createForm({\n  email: {\n    value: '',\n    validate: (v) => (v.includes('@') ? undefined : 'Invalid email'),\n  },\n})\n\n<form on-submit=${form.handleSubmit((values) => console.log(values))}>\n  <input bind-value=${form.fields.email} />\n  <span>${form.fields.email.error()}</span>\n</form>",
    path: "/forms",
  },
  {
    id: "createLifecycle",
    pkg: "@jacare/core",
    groupId: "lifecycle",
    name: "createLifecycle",
    importLine: "import { createLifecycle } from '@jacare/core'",
    example: "import { createLifecycle } from '@jacare/core'\n\nexport const lifecycle = createLifecycle({\n  onMount() { console.log('mounted') },\n  onActivate() { console.log('visible') },\n  onDeactivate() { console.log('hidden') },\n  onUnmount() { console.log('gone') },\n})",
    path: "/lifecycle",
  },
  {
    id: "registerScope",
    pkg: "@jacare/core",
    groupId: "lifecycle",
    name: "registerScope",
    importLine: "import { registerScope } from '@jacare/core'",
    example: "import { createLifecycle, registerScope } from '@jacare/core'\n\nexport const lifecycle = createLifecycle({\n  onActivate() {\n    return registerScope('draft', 'Draft', () => draft())\n  },\n})",
    path: "/lifecycle",
  },
  {
    id: "renderToString",
    pkg: "@jacare/core",
    groupId: "ssr",
    name: "renderToString",
    importLine: "import { renderToString } from '@jacare/core'",
    example: "import { renderToString } from '@jacare/core'\nimport { render } from './Page.jcr'\n\nconst html = renderToString(render, { title: 'Hi' })",
    path: "/ssr",
  },
  {
    id: "renderToStream",
    pkg: "@jacare/core",
    groupId: "ssr",
    name: "renderToStream",
    importLine: "import { renderToStream } from '@jacare/core'",
    example: "import { renderToStream } from '@jacare/core'\nimport { render } from './Page.jcr'\n\nfor await (const chunk of renderToStream(render)) {\n  res.write(chunk)\n}",
    path: "/ssr",
  },
  {
    id: "resumeBindings",
    pkg: "@jacare/core",
    groupId: "ssr",
    name: "resumeBindings",
    importLine: "import { resumeBindings } from '@jacare/core'",
    example: "import { resumeBindings } from '@jacare/core'\n\nresumeBindings(rootEl, state)\n// Prefer resume() from the .jcr module in apps.",
    path: "/ssr",
  },
  {
    id: "mountIsland",
    pkg: "@jacare/core/island",
    groupId: "islands",
    name: "mountIsland",
    importLine: "import { mountIsland } from '@jacare/core/island'",
    example: "import { mountIsland } from '@jacare/core/island'\nimport Widget from './Widget.jcr'\n\nconst island = mountIsland('#slot', Widget, {\n  props: { start: 2 },\n  shadow: true,\n})\n\nisland.update({ start: 5 })\nisland()",
    path: "/island",
  },
  {
    id: "escapeHtml",
    pkg: "@jacare/core",
    groupId: "ssr",
    name: "escapeHtml",
    importLine: "import { escapeHtml } from '@jacare/core'",
    example: "import { escapeHtml } from '@jacare/core'\n\nescapeHtml('<script>')  // → '&lt;script&gt;'",
    path: "/ssr",
  },
  {
    id: "mount",
    pkg: ".jcr module",
    groupId: "ssrClient",
    name: "mount",
    importLine: "import { mount } from './Page.jcr'",
    example: "import { mount } from './Counter.jcr'\n\nconst dispose = mount(document.getElementById('app'), { start: 0 })\n// later: dispose()",
    path: "/module",
  },
  {
    id: "render",
    pkg: ".jcr module",
    groupId: "ssrClient",
    name: "render",
    importLine: "import { render } from './Page.jcr'",
    example: "import { render } from './Page.jcr'\n\nconst { html, state } = render({ title: 'Hi' })",
    path: "/ssr",
  },
  {
    id: "resume",
    pkg: ".jcr module",
    groupId: "ssrClient",
    name: "resume",
    importLine: "import { resume } from './Page.jcr'",
    example: "import { resume } from './Page.jcr'\n\nresume(document.getElementById('app'), window.__STATE__)",
    path: "/ssr",
  },
  {
    id: "enableDevtools",
    pkg: "@jacare/core",
    groupId: "devtoolsCore",
    name: "enableDevtools",
    importLine: "import { enableDevtools } from '@jacare/core'",
    example: "import { enableDevtools } from '@jacare/core'\n\nenableDevtools()\n// Prefer connectJacareDevtools from @jacare/devtools",
    path: "/tooling",
  },
  {
    id: "why",
    pkg: "@jacare/core",
    groupId: "devtoolsCore",
    name: "why",
    importLine: "import { why, whyLast, formatWhyChain } from '@jacare/core'",
    example: "import { why, formatWhyChain } from '@jacare/core'\n\nconst chain = why(document.querySelector('.badge'))\nconsole.log(formatWhyChain(chain))\n// With the page hook: $why($0) · $why.last()",
    path: "/why",
  },
  {
    id: "namePulse",
    pkg: "@jacare/core",
    groupId: "devtoolsCore",
    name: "namePulse",
    importLine: "import { namePulse } from '@jacare/core'",
    example: "import { pulse, namePulse } from '@jacare/core'\n\nconst count = pulse(0)\nnamePulse(count, 'count')",
    path: "/tooling",
  },
  {
    id: "getPulseGraph",
    pkg: "@jacare/core",
    groupId: "devtoolsCore",
    name: "getPulseGraph",
    importLine: "import { getPulseGraph } from '@jacare/core'",
    example: "import { getPulseGraph } from '@jacare/core'\n\nconst graph = getPulseGraph()\nconsole.log(graph.pulses)",
    path: "/tooling",
  },
  {
    id: "connectJacareDevtools",
    pkg: "@jacare/devtools",
    groupId: "devtoolsUi",
    name: "connectJacareDevtools",
    importLine: "import { connectJacareDevtools } from '@jacare/devtools'",
    example: "import { connectJacareDevtools } from '@jacare/devtools'\n\nconst stop = connectJacareDevtools({\n  position: 'bottom-right',\n  scope: true,\n  mesh: true,\n})\n// stop() removes the overlay",
    path: "/tooling",
  },
  {
    id: "compile",
    pkg: "@jacare/compiler",
    groupId: "compiler",
    name: "compile",
    importLine: "import { compile } from '@jacare/compiler'",
    example: "import { compile } from '@jacare/compiler'\n\nconst { code } = compile(source, {\n  filename: 'Page.jcr',\n  mode: 'module',\n})",
    path: "/tooling",
  },
  {
    id: "parseModule",
    pkg: "@jacare/compiler",
    groupId: "compiler",
    name: "parseModule / parseTemplate",
    importLine: "import { parseModule, parseTemplate } from '@jacare/compiler'",
    example: "import { parseModule } from '@jacare/compiler'\n\nconst ast = parseModule(source, 'Page.jcr')",
    path: "/tooling",
  },
  {
    id: "inspectTemplateBindings",
    pkg: "@jacare/compiler",
    groupId: "compiler",
    name: "inspectTemplateBindings",
    importLine: "import { inspectTemplateBindings } from '@jacare/compiler'",
    example: "import { inspectTemplateBindings } from '@jacare/compiler'\n\nconst sites = inspectTemplateBindings(source, 'Page.jcr')\nconsole.log(sites)",
    path: "/binding-ir",
  },
  {
    id: "lowerMountAst",
    pkg: "@jacare/compiler",
    groupId: "compiler",
    name: "lowerMountAst",
    importLine: "import { lowerMountAst } from '@jacare/compiler'",
    example: "import { parseTemplate, lowerMountAst } from '@jacare/compiler'\n\nconst ast = parseTemplate(viewSource)\nconst plan = lowerMountAst(ast)",
    path: "/binding-ir",
  },
  {
    id: "jacare",
    pkg: "@jacare/vite-plugin",
    groupId: "vite",
    name: "jacare",
    importLine: "import jacare from '@jacare/vite-plugin'",
    example: "import { defineConfig } from 'vite'\nimport jacare from '@jacare/vite-plugin'\n\nexport default defineConfig({\n  plugins: [jacare()],\n})",
    path: "/tooling",
  },
  {
    id: "createJacareViteConfig",
    pkg: "@jacare/vite-plugin",
    groupId: "vite",
    name: "createJacareViteConfig",
    importLine: "import { createJacareViteConfig } from '@jacare/vite-plugin'",
    example: "import { createJacareViteConfig } from '@jacare/vite-plugin'\n\nexport default createJacareViteConfig({\n  title: 'My App',\n})",
    path: "/tooling",
  },
  {
    id: "jacareMeta",
    pkg: "@jacare/meta",
    groupId: "meta",
    name: "jacareMeta",
    importLine: "import { jacareMeta } from '@jacare/meta/vite'",
    example: "import { jacareMeta } from '@jacare/meta/vite'\n\nplugins: [jacareMeta({ pagesDir: 'src/pages' })]",
    path: "/helpers",
  },
  {
    id: "discoverRoutes",
    pkg: "@jacare/meta",
    groupId: "meta",
    name: "discoverRoutes",
    importLine: "import { discoverRoutes } from '@jacare/meta/vite'",
    example: "import { discoverRoutes } from '@jacare/meta/vite'\n\nconst routes = discoverRoutes({ pagesDir: 'src/pages' })\n// → [{ path: '/', file: '…' }, …]",
    path: "/helpers",
  },
  {
    id: "createJacareApp",
    pkg: "@jacare/meta",
    groupId: "meta",
    name: "createJacareApp",
    importLine: "import { createJacareApp } from '@jacare/meta'",
    example: "import { createJacareApp } from '@jacare/meta'\n\nconst app = createJacareApp({\n  layout: Shell,\n  screens: { '/': Home },\n})\napp.attach(document.getElementById('app'))",
    path: "/helpers",
  },
  {
    id: "jacareCli",
    pkg: "@jacare/cli",
    groupId: "cli",
    name: "jacare new / dev / build / check",
    importLine: "(CLI — not a JS import)",
    example: "npm create jacare@latest my-app\njacare new my-app --template=todo\njacare dev\njacare build\njacare check --bindings",
    path: "/tooling",
  },
  {
    id: "exportView",
    pkg: ".jcr syntax",
    groupId: "language",
    name: "export <view>",
    importLine: "(required module block)",
    example: "import { pulse } from '@jacare/core'\n\nconst count = pulse(0)\n\nexport <view>\n  <button on-click=${() => count.update(n => n + 1)}>\n    ${count}\n  </button>\n</view>",
    path: "/language",
  },
  {
    id: "exportStyle",
    pkg: ".jcr syntax",
    groupId: "language",
    name: "export <style>",
    importLine: "(optional scoped CSS)",
    example: "export <style>\n  button { color: green; }\n</style>",
    path: "/language",
  },
  {
    id: "exportContract",
    pkg: ".jcr syntax",
    groupId: "language",
    name: "export <contract>",
    importLine: "(optional contract surface)",
    example: "export <contract>\n  props: { title: string }\n</contract>",
    path: "/language",
  },
  {
    id: "events",
    pkg: ".jcr syntax",
    groupId: "language",
    name: "on-* / @* events",
    importLine: "(template attributes)",
    example: "<button on-click=${() => count.update(n => n + 1)}>\n  Click\n</button>",
    path: "/events",
  },
  {
    id: "debugTag",
    pkg: ".jcr syntax",
    groupId: "language",
    name: "<debug>",
    importLine: "(template tag — stripped in prod)",
    example: "<debug count=${count} cart=${cart}></debug>",
    path: "/debug",
  },
]
